## Problem 3 - Data analysis (4 points)

In this problem we will explore our temperature data by comparing spring temperatures between Helsinki Kumpula and Rovaniemi. To do this we'll use some conditions to extract subsets of our data and then analyse these subsets using basic pandas functions. Please perform the tasks below by writing your code into the codeblocks in each section.

### Tips for completing this problem

- Use **exactly** the same variable names as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-5-problem-3.ipynb` file (this file).
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail. 

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Calculating the median temperatures for Mactan and Hinatuan for March-May of 2018
- Selecting temperatures for April and December 2018 in separate dataframes for each location
- Printing out some summary values for each month (April, December) and location (Mactan, Hinatuan)
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook and data files to your GitHub repository for this week's exercise

### Part 1 (0 points)

First, you need to load the data from Problem 2.

- Read in the csv files generated in Problem 2 to the variables `mactan` and `hinatuan`

In [1]:
#import panda 
import pandas as pd

In [2]:
#read the mactan and hinatuan csvs 
mactan = pd.read_csv("Mactan_temps_2019-01_2020-12.csv")
hinatuan = pd.read_csv("Rovaniemi_temps_2019-01_2020-12.csv")

In [3]:
print(mactan.head())
print('')
print(hinatuan.head())

       STATION        DATE   TEMP    MAX    MIN
0  RPM00098646  2017-01-01  79.70  86.00    NaN
1  RPM00098646  2017-01-02  79.88  85.64    NaN
2  RPM00098646  2017-01-03  82.40  88.52  76.64
3  RPM00098646  2017-01-04  82.04  89.24    NaN
4  RPM00098646  2017-01-05  81.32  88.52  77.00

       STATION        DATE   TEMP    MAX    MIN
0  RP000098755  2017-01-01  80.06  84.20  75.20
1  RP000098755  2017-01-02  80.78  85.64  75.92
2  RP000098755  2017-01-03  79.88  85.28    NaN
3  RP000098755  2017-01-04  80.60  86.36  75.38
4  RP000098755  2017-01-05  77.72  89.06    NaN

### Part 2 (1 points)

Next you can find some median temperature values for the period the data covers.

- What was the median Celsius temperature during the observed period in:
    - Mactan, Cebu? (store the answer in a variable `mactan_median`)
    - Hinatuan, Surigao del Sur? (store the answer in a variable `hinatuan_median`)

In [4]:
#getting the media values of the temperature in each data frame 
mactan_median = mactan["TEMP"].median()
hinatuan_median = hinatuan["TEMP"].median()

In [5]:
# Prints the median temperatures
print(f"Mactan median: {mactan_median}")
print(f"Hinatuan median: {hinatuan_median}")

Mactan median: 82.58
Hinatuan median: 81.14

### Part 3 (2 points)

The median temperatures above consider data from the entire "summer" (Mar-May), hence the differences might not be so clear. Let's now find out the mean temperatures from March and May 2018 in Mactan and Hinatuan.

- From the `mactan` and `hinatuan` DataFrames, select the rows where values of the `DATE` column are from March 2018
    - Assign these selected rows into the variables `mactan_mar` and `hinatuan_mar` (you can check the [hints](https://geo-python.github.io/site/lessons/L5/exercise-5.html) for help!)
- Repeat the procedure for the month of May and assign those values into variables to `mactan_may` and `hinatuan_may`

In [6]:
# Select the subset of the Mactan and Hinatuan data for the 3rd and 5th month
mactan_mar = mactan.loc[mactan['DATE'] >= '2017-03-01']
hinatuan_mar = hinatuan.loc[hinatuan['DATE'] >= '2017-03-01']

mactan_may = mactan.loc[mactan['DATE'] >= '2017-05-01']
hinatuan_may = hinatuan.loc[hinatuan['DATE'] >= '2017-05-01']

Check that the subsets look ok:

In [7]:
print(f"First values in March, Mactan:\n{mactan_mar.head()}\n")
print(f"Last values in March, Mactan:\n{mactan_mar.tail()}")

First values in March, Mactan:
        STATION        DATE   TEMP    MAX    MIN
59  RPM00098646  2017-03-01  81.50  87.80  75.20
60  RPM00098646  2017-03-02  81.68  88.70  76.82
61  RPM00098646  2017-03-03  80.96  88.34    NaN
62  RPM00098646  2017-03-04  81.32  88.70  75.56
63  RPM00098646  2017-03-05  82.04    NaN  76.46

Last values in March, Mactan:
          STATION        DATE   TEMP    MAX    MIN
1456  RPM00098646  2020-12-27  80.96  86.72  75.38
1457  RPM00098646  2020-12-28  78.62    NaN    NaN
1458  RPM00098646  2020-12-29  82.04  89.24  75.38
1459  RPM00098646  2020-12-30  81.86  87.80    NaN
1460  RPM00098646  2020-12-31  81.68  86.54    NaN

In [8]:
print(f"First values in May, Mactan:\n{mactan_may.head()}\n")
print(f"Last values in May, Mactan:\n{mactan_may.tail()}")

First values in May, Mactan:
         STATION        DATE   TEMP    MAX    MIN
120  RPM00098646  2017-05-01  85.10  92.30  78.08
121  RPM00098646  2017-05-02  86.00  94.10  79.16
122  RPM00098646  2017-05-03  82.58  92.30    NaN
123  RPM00098646  2017-05-04  84.92  90.32  74.30
124  RPM00098646  2017-05-05  85.46  90.68  79.88

Last values in May, Mactan:
          STATION        DATE   TEMP    MAX    MIN
1456  RPM00098646  2020-12-27  80.96  86.72  75.38
1457  RPM00098646  2020-12-28  78.62    NaN    NaN
1458  RPM00098646  2020-12-29  82.04  89.24  75.38
1459  RPM00098646  2020-12-30  81.86  87.80    NaN
1460  RPM00098646  2020-12-31  81.68  86.54    NaN

In [9]:
print(f"First values in March, Hinatuan:\n{hinatuan_mar.head()}\n")
print(f"Last values in March, Hinatuan:\n{hinatuan_mar.tail()}")

First values in March, Hinatuan:
        STATION        DATE   TEMP    MAX    MIN
59  RP000098755  2017-03-01  80.06  86.18    NaN
60  RP000098755  2017-03-02  76.46  81.50  73.40
61  RP000098755  2017-03-03  77.18  82.76  73.40
62  RP000098755  2017-03-04  80.24  85.46  74.30
63  RP000098755  2017-03-05  76.64  80.24  74.12

Last values in March, Hinatuan:
          STATION        DATE   TEMP    MAX    MIN
1455  RP000098755  2020-12-27  82.58  90.32  74.48
1456  RP000098755  2020-12-28  80.78  85.64    NaN
1457  RP000098755  2020-12-29  81.68  89.24  76.28
1458  RP000098755  2020-12-30  80.42  86.72  76.82
1459  RP000098755  2020-12-31  80.24  86.36    NaN

In [10]:
print(f"First values in May, Hinatuan:\n{hinatuan_may.head()}\n")
print(f"Last values in May, Hinatuan:\n{hinatuan_may.tail()}")

First values in May, Hinatuan:
         STATION        DATE   TEMP    MAX   MIN
120  RP000098755  2017-05-01  83.48    NaN  77.0
121  RP000098755  2017-05-02  82.94  88.88  77.0
122  RP000098755  2017-05-03  82.22  90.68   NaN
123  RP000098755  2017-05-04  82.94  91.58  76.1
124  RP000098755  2017-05-05  81.86  92.48  76.1

Last values in May, Hinatuan:
          STATION        DATE   TEMP    MAX    MIN
1455  RP000098755  2020-12-27  82.58  90.32  74.48
1456  RP000098755  2020-12-28  80.78  85.64    NaN
1457  RP000098755  2020-12-29  81.68  89.24  76.28
1458  RP000098755  2020-12-30  80.42  86.72  76.82
1459  RP000098755  2020-12-31  80.24  86.36    NaN

### Part 4 (1 point)

Now you can make your temperature data from both locations and months easier to compare by printing out a few useful values.

- Use the `print()` function to show the mean, min and max Celsius temperatures for both places in March and May using the new subset dataframes (`mactan_mar`, `hinatuan_mar`, `mactan_may`, and `hinatuan_may`).

In [11]:
# print the mean, min and max temp for the march and may values in hinatuan and mactan
# Mactan March
print ("Mactan March Temp Data")
mactan_mar_mean= mactan_mar["TEMP"].mean()
mactan_mar_max = mactan_mar["TEMP"].max()
mactan_mar_min= mactan_mar["TEMP"].min()
print(f"Mean:{mactan_mar_mean}\nMin:{mactan_mar_min}\nMax:{mactan_mar_max}")

print (' ')

#Mactan May
print ("Mactan May Temp Data")
mactan_may_mean= mactan_may["TEMP"].mean()
mactan_may_max = mactan_may["TEMP"].max()
mactan_may_min= mactan_may["TEMP"].min()
print(f"Mean:{mactan_may_mean}\nMin:{mactan_may_min}\nMax:{mactan_may_max}")

print (' ')

# Hinatuan March
print ("Hinatuan March Temp Data")
hinatuan_mar_mean= hinatuan_mar["TEMP"].mean()
hinatuan_mar_max = hinatuan_mar["TEMP"].max()
hinatuan_mar_min= hinatuan_mar["TEMP"].min()
print(f"Mean:{hinatuan_mar_mean}\nMin:{hinatuan_mar_min}\nMax:{hinatuan_mar_max}")

print (' ')

# Hinatuan May
print ("Hinatuan May Temp Data")
hinatuan_may_mean= hinatuan_may["TEMP"].mean()
hinatuan_may_max = hinatuan_may["TEMP"].max()
hinatuan_may_min= hinatuan_may["TEMP"].min()
print(f"Mean:{hinatuan_may_mean}\nMin:{hinatuan_may_min}\nMax:{hinatuan_may_max}")

Mactan March Temp Data
Mean:82.70582025677604
Min:73.04
Max:87.98

Mactan May Temp Data
Mean:82.7468456375839
Min:73.04
Max:87.98

Hinatuan March Temp Data
Mean:81.28222698072804
Min:74.12
Max:86.54

Hinatuan May Temp Data
Mean:81.30885074626866
Min:74.12
Max:86.54

### Problem 3 summary

In the spirit of [knowledge discovery](http://researcher.ibm.com/researcher/view_group.php?id=144), let's briefly interpret the results of the data analysis in Problem 3. Please answer the following questions based on the data analysis results from this problem:

- Does there seem to be a large difference in temperatures between the months?
- Is Hinatuan a much cooler place than Mactan?

Also, be sure to:

- Check that your code includes informative comments explaining what your code does
- Commit and push your changes to your GitHub repository for Exercise 5

- No, the differences between the temperatures is really small. 
- Hintauan is slightly cooler than Mactan.

Submitted by: Clarice and Hannagene

### On to Problem 4 (*optional*)

Now you can continue to the *optional* [Problem 4: Data analysis](Exercise-5-problem-4.ipynb)